### ISSUE TITLE
Login failed: Not Authorized

### ISSUE THREAD

**Issue by ckvtvm-arch** [jbossdemocentral/rhdm7-loan-demo#13]
I am trying this for last several days, but not successful. can you please help in logging in for the first time. I was able to do so in the past, but now i am failing.

Added the user name and password as shown below:

./add-user.sh -a --user --password --role admin

Added user 'encounter' to file '/opt/eap/standalone/configuration/application-users.properties'
Added user 'encounter' to file '/opt/eap/domain/configuration/application-users.properties'
Added user 'encounter' with groups admin to file '/opt/eap/standalone/configuration/application-roles.properties'
Added user 'encounter' with groups admin to file '/opt/eap/domain/configuration/application-roles.properties'

Login failed: Not Authorized

**Comment by ckvtvm-arch** [comment]
Resolved

**Comment by bxc2739** [comment]
What did you have to add/change?
